name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout the code
        uses: actions/checkout@v6

      - name: set up node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: install dependencies
        run: npm ci

      - name: build the app
        run: npm run build

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v3"

      - name: build docker image and push it to google artifact registy
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-508611/notely-ar-repo/notely:latest .
